[features]
seeds = false
skip-lint = false
[programs.devnet]
spl_staking = "GfDz6c7PsBK3yFLXAaxmmXsXH1A69j4EFcZ7RUrJMW13"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/work/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
